### ISSUE TITLE
Unable to connect to testnet

### ISSUE THREAD

**Issue by timothyTheCoder** [XRPLF/xrpl-dev-portal#1000]
While the code was working couple of days ago, suddenly unable to connect to the testnet. Anyone knows why? Test wallet is 
rnmQWJRuF4E6emRFrSWh891fc5h9kmSzrD 

        feign.RetryableException: Connection refused executing POST https://s.altnet.rippletest.net:51234/
	at feign.FeignException.errorExecuting(FeignException.java:249)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:129)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy66.postRpcRequest(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:114)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:728)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:75)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy66.send(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:93)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:728)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:75)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy66.send(Unknown Source)
	at org.xrpl.xrpl4j.client.XrplClient.accountInfo(XrplClient.java:269)

Thanks in advance.

**Comment by ryangyoung** [comment]
Try the other Testnet server at `https://35.158.96.209:51234`. The server you're trying to hit (`https://s.altnet.rippletest.net:51234/`) is currently down and is a known issue: https://github.com/ripple/ripple-lib/issues/1381

**Comment by timothyTheCoder** [comment]
Ok thanks. When using https://35.158.96.209:51234, I now get:

feign.RetryableException: No subject alternative names matching IP address 35.158.96.209 found executing POST https://35.158.96.209:51234/

I can connect to the https://s.devnet.rippletest.net:51234/ so I guess it is not a real issue and will code using that server as long as the tense server is down.

**Comment by mDuo13** [comment]
As [I commented over there](https://github.com/ripple/ripple-lib/issues/1381#issuecomment-797863528), this is resolved now.
