### ISSUE TITLE
failed to build on windows 10

### ISSUE THREAD

**Issue by dolphinsd** [XRPLF/xrpl-dev-portal#599]
When tried to build with dactyl on windows 10, got python errors:

Traceback (most recent call last):
  File "c:\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python37-32\Scripts\dactyl_build.exe\__main__.py", line 9, in <module>
  File "c:\python\python37-32\lib\site-packages\dactyl\dactyl_build.py", line 1099, in dispatch_main
    config = DactylConfig(cli.cli_args)
  File "c:\python\python37-32\lib\site-packages\dactyl\config.py", line 40, in __init__
    self.load_config_from_file(DEFAULT_CONFIG_FILE)
  File "c:\python\python37-32\lib\site-packages\dactyl\config.py", line 109, in load_config_from_file
    page["name"] = guess_title_from_md_file(page_path)
  File "c:\python\python37-32\lib\site-packages\dactyl\common.py", line 49, in guess_title_from_md_file
    line1 = f.readline()
  File "c:\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 371: character maps to <undefined>

**Comment by mDuo13** [comment]
Dactyl is not officially supported or regularly tested on Windows, but I have heard of people getting it working.

I guess it looks like [this system codec issue](https://stackoverflow.com/questions/30750843/python-3-unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d) is the problem; your system is assuming latin-1 (aka cp1252) encoding rather than utf-8. Most likely the fix would be a change to [Dactyl](https://github.com/ripple/dactyl/) to assume utf-8 encoding. Maybe it's safe to do that by default, maybe it'd be better to use the system default and fall back to utf-8 if it fails. I'll look into it.

In the meantime, you might be able to build (somewhat) successfully using the `--bypass_errors` flag when running Dactyl. Based on your traceback, it might not actually be able to read a lot of the content files, so I wouldn't expect much.
